"""Create ApiConfig table

Revision ID: 63028e9844c3
Revises: 
Create Date: 2025-04-17 15:06:46.419247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63028e9844c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('service_account_file', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('to_recipients',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('cc_recipients',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('bcc_recipients',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('category_id',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('category_name',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('priority_ai',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('has_attachments',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('attachments',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('internet_message_id',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('conversation_id',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('summary',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('body_preview',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('body_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('web_link',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('categories',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('interval_hours',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('interval_minutes',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('cron_hour',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('cron_minute',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('cron_minute',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('cron_hour',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('interval_minutes',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('interval_hours',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('categories',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('web_link',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('body_text',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('body_preview',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('conversation_id',
               existing_type=sa.String(length=255),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('internet_message_id',
               existing_type=sa.String(length=255),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('attachments',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('has_attachments',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('priority_ai',
               existing_type=sa.String(length=255),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('category_name',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('bcc_recipients',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('cc_recipients',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('to_recipients',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    op.drop_table('api_configs')
    # ### end Alembic commands ###
